### ISSUE TITLE
Error on step: rMAP is will now perform Variant Calling

### ISSUE THREAD

**Issue by jpcartailler** [GunzIvan28/rMAP#10]
Greetings,
Thank you to the author(s) for putting this package together! I have a few issues I'm hoping you can shed light on.

We have rMAP set up on a Linux HPC, using the conda approach in the docs. 

We are executing the program with:
```
rMAP \
-t 8 \
--input /private/data/test/ \
--output /private/results/02-rmap-debugging \
--reference /private/data/Staph_CP0000461.gbk \
--quality --assembly shovill --amr --varcall --trim --phylogeny --pangenome --gen-ele
```

At the rMAP step, we are seeing:
```
rMAP is will now perform Variant Calling...[0m
[1;31m.gbk found !!! Annotation Mode Enabled...Preparing Annotation files...[0m
Traceback (most recent call last):
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/bin/biopython.convert", line 10, in <module>
    sys.exit(main())
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/site-packages/biopython_convert/__main__.py", line 7, in main
    convert(*get_args(sys.argv[1:]))
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/site-packages/biopython_convert/__init__.py", line 194, in convert
    with input_path.open("r") as handle:
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/private/results/02-rmap-debugging/references/private/data/Staph_CP0000461.gbk'
Traceback (most recent call last):
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/bin/biopython.convert", line 10, in <module>
    sys.exit(main())
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/site-packages/biopython_convert/__main__.py", line 7, in main
    convert(*get_args(sys.argv[1:]))
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/site-packages/biopython_convert/__init__.py", line 194, in convert
    with input_path.open("r") as handle:
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/private/results/02-rmap-debugging/references/private/data/Staph_CP0000461.gbk'
[bwa_idx_build] fail to open file '/private/results/02-rmap-debugging/references/*.fa' : No such file or directory
[E::fai_build3_core] Failed to open the file /private/results/02-rmap-debugging/references/*.fa
[faidx] Could not build fai index /private/results/02-rmap-debugging/references/*.fa.fai
[1;34mProcessing sample: 7285-NS-10[0m
[E::bwa_idx_load_from_disk] fail to locate the index files
[samclip] ERROR: Can't see '/private/results/02-rmap-debugging/references/*.fai' index. Run 'samtools faidx /private/results/02-rmap-debugging/references/*.fai' ?
samtools sort: failed to read header from "-"
[bam_mating_core] ERROR: Couldn't read header
samtools sort: failed to read header from "-"
[markdup] error reading header
samtools index: "/private/results/02-rmap-debugging/variant_calling/7285-NS-10.mrkdup.bam" is in a format that cannot be usefully indexed
```

The first error is `FileNotFoundError: [Errno 2] No such file or directory: '/private/results/02-rmap-debugging/references/private/data/Staph_CP0000461.gbk'`, which appears to be concatenating two paths together:
1. /private/results/02-rmap-debugging/references
2. /private/data/Staph_CP0000461.gbk

I suspect the downstream errors are due to this initial error, but I have no idea why the paths would get concatenated as such. We provided the paths as absolute.

Also, is there a way to resume the job from the last point of failure, vs. repeating from the beginning?

Cheers!

**Comment by jpcartailler** [comment]
Been reading through the `bin/rMAP` source, and I think I found the issue.

The following concatenates two paths together:
```
biopython.convert $TEMP/${REFERENCE} genbank -i $TEMP/$x.fa fasta
```
The code really expects `${REFERENCE}` to be a file (no path, which can only work if stored in home directory), but we provided a full path. There's a little more to it than above, but am currently putting some fixes in place. Happy to contribute back, if you're OK with pull requests.

**Comment by GunzIvan28** [comment]
@c5creative, 
We will be delighted to work with you. If it is cool, I could add you as a collaborator and then you can create a branch from there from which I can review your changes and pull to the master. Let me know how that sounds.


Ivan

**Comment by jpcartailler** [comment]
Sure, that sounds great. It'll be a little easier maintaining one repo and just switch branches.

**Comment by GunzIvan28** [comment]
@c5creative,
Based on your previous issue regarding this:
```
rMAP is will now perform Variant Calling...�[0m
�[1;31m.gbk found !!! Annotation Mode Enabled...Preparing Annotation files...�[0m
Traceback (most recent call last):
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/bin/biopython.convert", line 10, in <module>
    sys.exit(main())
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/site-packages/biopython_convert/__main__.py", line 7, in main
    convert(*get_args(sys.argv[1:]))
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/site-packages/biopython_convert/__init__.py", line 194, in convert
    with input_path.open("r") as handle:
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/private/results/02-rmap-debugging/references/private/data/Staph_CP0000461.gbk'
Traceback (most recent call last):
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/bin/biopython.convert", line 10, in <module>
    sys.exit(main())
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/site-packages/biopython_convert/__main__.py", line 7, in main
    convert(*get_args(sys.argv[1:]))
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/site-packages/biopython_convert/__init__.py", line 194, in convert
    with input_path.open("r") as handle:
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
  File "/data/p_magnuson_lab/conda/envs/rMAP-1.0/lib/python3.7/pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/private/results/02-rmap-debugging/references/private/data/Staph_CP0000461.gbk'
[bwa_idx_build] fail to open file '/private/results/02-rmap-debugging/references/*.fa' : No such file or directory
[E::fai_build3_core] Failed to open the file /private/results/02-rmap-debugging/references/*.fa
[faidx] Could not build fai index /private/results/02-rmap-debugging/references/*.fa.fai
�[1;34mProcessing sample: 7285-NS-10�[0m
[E::bwa_idx_load_from_disk] fail to locate the index files
[samclip] ERROR: Can't see '/private/results/02-rmap-debugging/references/*.fai' index. Run 'samtools faidx /private/results/02-rmap-debugging/references/*.fai' ?
samtools sort: failed to read header from "-"
[bam_mating_core] ERROR: Couldn't read header
samtools sort: failed to read header from "-"
[markdup] error reading header
samtools index: "/private/results/02-rmap-debugging/variant_calling/7285-NS-10.mrkdup.bam" is in a format that cannot be usefully indexed
```

I noticed when you were specifying your reference genome via the `--reference /private/data/Staph_CP0000461.gbk` channel, the issue could have come up because of the nomenclature of `Staph_CP0000461.gbk`. The script in rMAP that extracts the reference genome name doesn't take into account special symbols (for this case _ ). In fact, it takes in a reference genome with a single word with its extension for example you can rename that reference to `Staph.gbk` or `CP0000461.gbk`. Try to run either of these and let me know if this fixes your issue.


Ivan
